kind: Service
apiVersion: v1
metadata:
  name: gregor-hires-openapi-ui
spec:
  selector:
    pod: gregor-hires-project-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081