apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: gregor-hires-project-evidence
  includeSelectors: true
  includeTemplates: true

resources:
- ../../../apps/gregor-hires-project-ufe
- ../../../apps/gregor-hires-project-webapi


components:
- ../../../components/version-release