apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: gregor-hires-project-ufe-content
spec:
  microFrontend: gregor-hires-project-ufe
  element: gregor-hires-project-evidence-app
  attributes:
    - name: base-path
      value: /gregor-hires-project-evidence/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?gregor-hires-project-evidence(/.*)?$"